export { SignIn } from './SignIn/SignIn'
export { Login } from './Login/Login'
export { SignUp } from './SignUp/SignUp'
export { Splash } from "./Splash/Splash"
export { Home } from './Home/Home'
export { Album } from './Album/Album'
export { AllAlbum } from "./Artist/AllAlbum"
export { Artist } from './Artist/Artist'
export { Playing } from './Playing/Playing'
export { Favourite } from './Favourite/Favourite'
export { Playlist } from './Playlist/PLaylist'
export { SearchDefault } from './Search/SearchDefault'
export { SearchFocused } from './Search/SearchFocused'
export { SearchResult } from './Search/SearchResult'